### ISSUE TITLE
Difference between `HasValidBundle` and `InvalidBundleContent`?

### ISSUE THREAD

**Issue by joelanford** [operator-framework/rukpak#518] opened 2022-08-22 20:34 UTC
I see that our plain and helm provisioners use both `HasValidBundle` and `InvalidBundleContent` condition types. At a glance these seem duplicative, which could cause UX confusion.

I propose that we remove `InvalidBundleContent` and use `HasValidBundle == "False"` in its place.

**Comment by timflannagan** [comment] 2022-08-22 20:37
Do we need multiple bundle conditions at the BD controller level? Can we have a single Unpacked condition, and derive any validation or unpack failures there?

**Comment by joelanford** [comment] 2022-08-22 20:40
Yeah, that's essentially what I'm saying. If there's a better name than `HasValidBundle`, we can change that too. For this issue I was primarily focused on "let's have one rather than two", and less on "what should the name of the one be".

**Comment by timflannagan** [comment] 2022-08-22 20:47
Related to https://github.com/operator-framework/rukpak/issues/333 and https://github.com/operator-framework/rukpak/issues/331. The first issue looks like a potential duplicate of this one?

**Closed** 2022-08-23 13:44 UTC
Labels: priority/important-soon
